routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::redirect('/', '/post');

Auth::routes();

Route::middleware('foo.set')->group(function () {
    Route::get('/setfoo', 'FooController@showSetFooForm');
    Route::post('/setfoo', 'FooController@setFooToSession');
});

Route::middleware('foo')->group(function () {
    Route::get('/home', 'HomeController@index')->name('home');

    Route::middleware('admin')->group(function () {
        Route::get('category/{category?}', 'CategoryController@index');
        Route::post('category/{category?}', 'CategoryController@store');
        Route::delete('category/{category}', 'CategoryController@destroy');

        Route::get('user', 'UserController@index');
        Route::get('user/post/{user}', 'UserController@showUserPost');
    });

    Route::get('post/category/{slug}', 'CategoryController@showPostByCategory');
    Route::get('post/my', 'PostController@showMyPost');
    Route::resource('post', 'PostController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $fillable = [
        'title',
        'body',
        'image',
        'publish_time',
        'user_id'
    ];

    /*protected $casts = [
        'publish_time' => 'datetime',
    ];*/

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    public function category()
    {
        return $this->belongsToMany('App\Category');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Http\Requests\PostCreateRequest;
use App\Http\Requests\PostUpdateRequest;
use App\Post;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\File;

class PostController extends Controller
{
    public function _construct()
    {
        $this->middleware('auth')->except(['index', 'show']);
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data['posts'] = Post::with('user', 'category')
                            ->where('publish_time','<=', date('Y-m-d H:ia'))
                            ->orderBy('publish_time')
                            ->simplePaginate();

        $data['categories'] = Category::all();
        return view('post.all', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data['categories'] = Category::all();
        return view('post.create', $data);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param PostCreateRequest $request
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function store(PostCreateRequest $request)
    {
        $data = $request->all();
        $data['user_id'] = Auth::id();

        if ($request->hasFile('image')) {
            $data['image'] = $request->image->store('post');
        }

        $post = Post::create($data);

        $post->category()->sync($request->category_id);

        return redirect('post')->with('success', "Post Created successfully");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {
        $data['post'] = $post;
        $data['categories'] = Category::all();
        return view('post.show', $data);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function edit(Post $post)
    {
        $this->authorize('update', $post);

        $data['post'] = Post::with('user', 'category')->whereId($post->id)->first();
        $data['categories'] = Category::all();
        return view('post.edit', $data);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param PostUpdateRequest $request
     * @param  \App\Post $post
     * @return \Illuminate\Http\RedirectResponse
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function update(PostUpdateRequest $request, Post $post)
    {
        $this->authorize('update', $post);

        $data = $request->all();

        if (empty($request->publish_time)) {
            unset($data['publish_time']);
        }

        if ($request->hasFile('image')) {
            if (File::exists(public_path('storage/'.$post->image))) {
                File::delete(public_path('storage/'.$post->image));
                $data['image'] = $request->image->store('post');
            }
        }

        $post->update($data);

        $post->category()->sync($request->category_id);

        return redirect()->back()->with('success', 'Post Updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Post $post
     * @return \Illuminate\Http\Response
     * @throws \Exception
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function destroy(Post $post)
    {
        $this->authorize('update', $post);

        if (File::exists(public_path('storage/'.$post->image))) {
            File::delete(public_path('storage/'.$post->image));
        }

        $post->category()->detach($post->id);
        $post->delete();

        return redirect('post', 'success', "Post deleted successfully");
    }

    public function showMyPost()
    {
        $data['posts'] = Post::with('user', 'category')
            ->where('user_id',Auth::id())
            ->orderBy('publish_time')
            ->simplePaginate();

        $data['categories'] = Category::all();
        return view('post.my', $data);
    }
}

resources/views/post/all.blade.php
@extends('layouts.app')

@section('scripts')
    <script>
        function switchCategory(element) {
            location.href = '{{url('post/category')}}/' + element.value;
        }

    </script>
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @if (session()->get('success'))
                    <div class="alert alert-success text-center">
                        {{ session()->get('success') }}
                    </div>
                @endif
                @if (session()->get('error'))
                    <div class="alert alert-danger text-center">
                        {{ session()->get('error') }}
                    </div>
                @endif
            </div>
        </div>
        @if (count($posts) < 1)
            No post to show. <a href="{{ url('post/create') }}">Create One</a>
        @else
            <div class="row">
                <div class="col-md-3">
                    <div class="form-group">
                        <select class="form-control" onchange="switchCategory(this)">
                            <option value="">-Select Category-</option>
                            @foreach($categories as $category)
                                <option value="{{$category->slug}}" {{ request()->segment('3') == $category->slug ? 'selected' : "" }}>{{$category->name}}</option>
                            @endforeach
                        </select>
                    </div>
                </div>
                <div class="col-md-8"></div>
                <div class="col-md-1">
                    <a href="{{ url('post/create') }}">
                        <button class="btn btn-sm btn-primary">Create New</button>
                    </a>
                </div>
            </div>
        @endif

        <br/>
        @foreach($posts as $post)
            <div class="col-md-12">
                <div class="card mt-3">
                    <div class="card-header">
                        <div style="float: left;" class="mr-5">
                            {{ $post->title ?? 'Unknown' }} by
                            <b>{{ $post->user->id == auth()->id() ? 'You' : $post->user->name }}</b><br>
                            <small>{{ date('d M, Y H:ia', strtotime($post->publish_time)) }}</small>
                            <div>
                                @foreach($post->category as $postCategory)
                                    <label class="badge badge-primary">{{ $postCategory->name }}</label>
                                @endforeach
                            </div>
                        </div>
                        @can('update', $post)
                            <div style="float: left">
                                <a href="{{ url('post/'.$post->id.'/edit') }}" style="float: left" class="mr-1">
                                    <button class="btn btn-sm btn-success">Edit</button>
                                </a>
                                <form method="post" action="{{ url('post', $post->id) }}" style="float: left">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-danger"
                                            onclick="return confirm('Are you sure to delete?')">Delete
                                    </button>
                                </form>
                            </div>
                        @endcan
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-2">
                                <img src="{{ asset('storage/'.$post->image) }}" class="img img-thumbnail img-responsive"
                                     alt="post image">
                            </div>
                            <div class="col-md-10">
                                @if (strlen($post->body) > 200)
                                    {{ substr($post->body, 0, 200) }}.. <a href="{{ url('post', $post->id) }}"> Show
                                        More</a>
                                @else
                                    {{ $post->body }}
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
        <div class="row mt-5">
            <div class="col-md-5"></div>
            <div class="col-md-2">{{ $posts->links() }}</div>
            <div class="col-md-4"></div>
        </div>
    </div>
@endsection

resources/views/post/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Create Post</div>
                    @if (session()->get('success'))
                        <div class="alert alert-success text-center">
                            {{ session()->get('success') }}
                        </div>
                    @endif
                    @if (session()->get('error'))
                        <div class="alert alert-danger text-center">
                            {{ session()->get('error') }}
                        </div>
                    @endif
                    <div class="card-body">
                        <form method="POST" action="{{ route('post.store') }}" enctype="multipart/form-data">
                            @csrf

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Title</label>
                                <div class="col-md-8">
                                    <input id="name" type="text"
                                           class="form-control @error('title') is-invalid @enderror" name="title"
                                           value="{{ old('title') }}" required autofocus>

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Body</label>
                                <div class="col-md-8">
                                    <textarea id="summernote"
                                              class="form-control @error('body') is-invalid @enderror" name="body"
                                              required>{{ old('body') }}</textarea>

                                    @error('body')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Category</label>
                                <div class="col-md-8">
                                    <select name="category_id[]"
                                            class="form-control @error('category') is-invalid @enderror" multiple>
                                        <option>--Select Category--</option>
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}"
                                            @foreach(old('category_id') ?? [] as $cat)
                                                {{ $cat == $category->id ? 'selected' : '' }}
                                                @endforeach
                                            >{{ $category->name }}</option>
                                        @endforeach
                                    </select>

                                    @error('category')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Image</label>
                                <div class="col-md-8">
                                    <input type="file"
                                           class="form-control @error('image') is-invalid @enderror" name="image"
                                           required>

                                    @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Publish Time</label>
                                <div class="col-md-8">
                                    <input type="datetime-local"
                                           class="form-control @error('publish_time') is-invalid @enderror"
                                           name="publish_time"
                                           value="{{ old('publish_time', date('mm/dd/yyyy H:ia')) }}" required>

                                    @error('publish_time')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-3 offset-md-9">
                                    <button type="submit" class="btn btn-primary">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <div class="card">
                    <div class="card-header">Update Post</div>
                    @if (session()->get('success'))
                        <div class="alert alert-success text-center">
                            {{ session()->get('success') }}
                        </div>
                    @endif
                    @if (session()->get('error'))
                        <div class="alert alert-danger text-center">
                            {{ session()->get('error') }}
                        </div>
                    @endif
                    @if (count($errors->all()) > 0)
                        <div class="alert alert-danger text-center">
                            @foreach($errors->all() as $error)
                                <p class="text-danger" style="color: red;">{{ $error }}</p>
                            @endforeach
                        </div>
                    @endif
                    <div class="card-body">
                        <form method="POST" action="{{ route('post.update', $post->id) }}"
                              enctype="multipart/form-data">
                            @csrf
                            @method('PATCH')
                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Title</label>
                                <div class="col-md-8">
                                    <input id="name" type="text"
                                           class="form-control @error('title') is-invalid @enderror" name="title"
                                           value="{{ old('title', $post->title ?? '') }}" required autofocus>

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Body</label>
                                <div class="col-md-8">
                                    <textarea id="summernote"
                                              class="form-control @error('body') is-invalid @enderror" name="body"
                                              required>{{ old('body',$post->body ?? '') }}</textarea>

                                    @error('body')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Category</label>
                                <div class="col-md-8">
                                    <select name="category_id[]"
                                            class="form-control @error('category') is-invalid @enderror" multiple>
                                        <option>--Select Category--</option>
                                        @foreach($categories as $category)
                                            <option value="{{ $category->id }}"
                                            @foreach($post->category as $cat)
                                                {{ $cat->id == $category->id ? 'selected' : '' }}
                                            @endforeach
                                            >{{ $category->name }}</option>
                                        @endforeach
                                    </select>

                                    @error('category')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Image</label>
                                <div class="col-md-8">
                                    <input type="file"
                                           class="form-control @error('image') is-invalid @enderror" name="image">

                                    @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                    <img src="{{ asset('storage/'.$post->image) }}"
                                         class="img img-thumbnail img-responsive mt-2" alt="post image" height="100px" width="200px">
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-2 col-form-label text-md-right">Publish Time</label>
                                <div class="col-md-8">
                                    <input type="datetime-local"
                                           class="form-control @error('publish_time') is-invalid @enderror"
                                           name="publish_time"
                                           value="{{ old('publish_time') }}">
                                    <b>Currently set on: {{ date('m/d/y H:ia', strtotime($post->publish_time)) }}</b>

                                    @error('publish_time')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row mb-0">
                                <div class="col-md-3 offset-md-9">
                                    <button type="submit" class="btn btn-primary">
                                        Update
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/post/my.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                @if (session()->get('success'))
                    <div class="alert alert-success text-center">
                        {{ session()->get('success') }}
                    </div>
                @endif
                @if (session()->get('error'))
                    <div class="alert alert-danger text-center">
                        {{ session()->get('error') }}
                    </div>
                @endif
            </div>
        </div>
        @if (count($posts) < 1)
            No post to show. <a href="{{ url('post/create') }}">Create One</a>
        @else
            <div class="row">
                <div class="col-md-11"></div>
                <div class="col-md-1">
                    <a href="{{ url('post/create') }}">
                        <button class="btn btn-sm btn-primary">Create New</button>
                    </a>
                </div>
            </div>
        @endif

        <br/>
        @foreach($posts as $post)
            <div class="col-md-12">
                <div class="card mt-3">
                    <div class="card-header">
                        <div style="float: left;" class="mr-5">
                            {{ $post->title ?? 'Unknown' }} by
                            <b>{{ $post->user->id == auth()->id() ? 'You' : $post->user->name }}</b><br>
                            <small>{{ date('d M, Y H:ia', strtotime($post->publish_time)) }}</small>
                            @if ($post->publish_time <= date('Y-m-d H:ia'))
                                <label class="badge badge-success">Published</label>
                            @endif
                            <div>
                                @foreach($post->category as $postCategory)
                                    <label class="badge badge-primary">{{ $postCategory->name }}</label>
                                @endforeach
                            </div>
                        </div>
                        @can('update', $post)
                            <div style="float: left">
                                <a href="{{ url('post/'.$post->id.'/edit') }}" style="float: left" class="mr-1">
                                    <button class="btn btn-sm btn-success">Edit</button>
                                </a>
                                <form method="post" action="{{ url('post', $post->id) }}" style="float: left">
                                    @csrf
                                    @method('DELETE')
                                    <button type="submit" class="btn btn-sm btn-danger"
                                            onclick="return confirm('Are you sure to delete?')">Delete
                                    </button>
                                </form>
                            </div>
                        @endcan
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-2">
                                <img src="{{ asset('storage/'.$post->image) }}" class="img img-thumbnail img-responsive"
                                     alt="post image">
                            </div>
                            <div class="col-md-10">
                                @if (strlen($post->body) > 200)
                                    {{ substr($post->body, 0, 200) }}.. <a href="{{ url('post', $post->id) }}"> Show
                                        More</a>
                                @else
                                    {{ $post->body }}
                                @endif
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        @endforeach
        <div class="row mt-5">
            <div class="col-md-5"></div>
            <div class="col-md-2">{{ $posts->links() }}</div>
            <div class="col-md-4"></div>
        </div>
    </div>
@endsection